logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[web]
address = ":8081"

[docker]
domain = "packerbuilder.xyz"
watch = true


[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "scherer_stefan@icloud.com"
storage = "/storage/acme.json"
entryPoint = "https"
# caServer = "https://acme-staging.api.letsencrypt.org/directory"

[acme.httpchallenge]
entrypoint="http"

[[acme.domains]]
   main = "packerbuilder.xyz"
   sans = ["whoami.packerbuilder.xyz", "portainer.packerbuilder.xyz", "jenkins.packerbuilder.xyz", "grafana.packerbuilder.xyz" ]

